experiment_key_column:
    description: 'Column used to group samples to make pseudobulk.'
    value: 'batch'
anndata_cell_label:
    description: 'Anndata cell label column in obs slot.'
    value: 'label_machine'
differential_expression:
    run_process: true
    models:
        description: 'List of differential formula and params.
            All covariates in formula should be listed in either
                variable_continuous or variable_discrete.'
        mean_cp10k_filter: 1
        value:
            # - method: 'mast::singlecell::glmer'
            #   formula: '~ n_genes_by_counts + stimulated + disease_status + sex + age_binned + pct_counts_gene_group__mito_transcript + (1 | donor)'
            #   variable_target: 'stimulated'
            #   variable_continuous: 'n_genes_by_counts,age_binned,pct_counts_gene_group__mito_transcript'
            #   variable_discrete: 'sex,donor,stimulated,disease_status'
            #   variable_discrete_level: 'stimulated::Control,Stimulated;;sex::Male,Female,disease_status::Healthy,CD'
            #   pre_filter_genes: true
            #   proportion_covariate_column: 'label_machine'
            #   include_proportion_covariates: false
            - method: 'mast::singlecell::glmer'
              formula: '~ n_genes_by_counts + disease_status + sex + age_binned + pct_counts_gene_group__mito_transcript + (1 | donor)'
              variable_target: 'disease_status'
              variable_continuous: 'n_genes_by_counts,age_binned,pct_counts_gene_group__mito_transcript'
              variable_discrete: 'sex,donor,disease_status'
              variable_discrete_level: 'sex::Male,Female,disease_status::Healthy,CD'
              pre_filter_genes: true
              proportion_covariate_column: 'label_machine'
    de_merge_config:
        ihw_correction:
            run_process: false
            description: 'Run IHW to correct differential expression results.'
            value:
                covariates: 'cell_label,coef_value'
                alpha: 0.1
    de_plot_config:
        mean_expression_filter:
            description: 'For comparison plots, drop genes whose mean
                expression for a group in anndata_cell_label is < this value.
                Example: if gene A expression is 0 counts in cluster 1 and 10
                in cluster 2, it will be dropped from cluster 1 but not cluster
                2.'
            value:
                - 0.0
    fgsea_config:
        run_process: true
        description: 'Parameters to run fGSEA.'
        sample_size: 101
        score_type: 'std'
        value:
            - min_set_size: 1
              max_set_size: Inf
              eps: 0
              database: 'c2.cp.reactome'
