NUM_ITER: 200
FACTORS: [20,30,40,50,60,65,70,75,80,85,90,95,100,110,120]
DENSITY_THRESHOLDS: [0.05,0.1,2]

OUT_DIR: ./out
snakemake_parallel: True

consensus_factors: [90]

ANNDATA:
  ti_discovery: 
    path: /sc_ti_atlas/data/discovery_cohort.h5ad
    factorise_memory: 5000
  ti_replication: 
    path: sc_ti_atlas/data/replication_cohort.h5ad
    factorise_memory: 5000

CONSENSUS:
  True


####################
# Mostly unchanging
####################

SEED: 14
NUM_HV_GENES: 2000
NUM_ITER: 200
