name: sc_ti_atlas
channels:
  - conda-forge
  - bioconda
  - dylkot
dependencies:
  - nextflow=23.04
  - snakemake=6.0.5
  - numpy
  - numba
  - pandas=1.2.3
  - pyyaml=5.3.1
  - statsmodels
  - scanpy=1.9
  - scikit-learn
  - scipy
  - pip=20.2.3
  - pyyaml=5.3.1
  - leidenalg=0.8.3
  - harmonypy=0.0.5
  - tensorflow=2.4
  - scrublet=0.2.3
  - bbknn=1.4.1
  - kneed=0.7.0
  - keras=2.4
  - louvain=0.7.0
  - fastcluster
  - palettable
  - matplotlib=3.6
  - r-base=4.0.2
  - r-data.table=1.13.6
  - r-tidyverse=1.3.0
  - r-lme4=1.1
  - bioconductor-mast=1.16.0
  - bioconductor-deseq2=1.30.0
  - bioconductor-limma=3.46.0
  - bioconductor-edger=3.32.0
  - bioconductor-fgsea=1.16.0
  - bioconductor-kegg.db=3.2.4
  - bioconductor-genomicranges=1.42.0
  - bioconductor-rhdf5=2.34.0
  - cnmf=1.3.1
