name: sc_ti_atlas
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - nextflow=23.04
  - snakemake=6.0.5
  - numpy=1.20.2
  - numba=0.53.0=
  - pandas=1.2.3
  - pyyaml=5.3.1
  - statsmodels=0.12.0
  - scanpy=1.8.0
  - scikit-learn=0.24
  - scipy=1.5.2
  - pip=20.2.3
  - python=3.8.5
  - pyyaml=5.3.1
  - leidenalg=0.8.3
  - harmonypy=0.0.5
  - tensorflow-gpu=2.4.1
  - scrublet=0.2.3
  - bbknn=1.4.1
  - kneed=0.7.0
  - keras-gpu=2.4.3
  - louvain=0.7.0
  - fastcluster
  - palettable
  - r-base=4.0.2
  - r-data.table=1.13.6
  - r-tidyverse=1.3.0
  - r-lme4=1.1.2_7.1
  - bioconductor-mast=1.16.0
  - bioconductor-deseq2=1.30.0
  - bioconductor-limma=3.46.0
  - bioconductor-edger=3.32.0
  - bioconductor-fgsea=1.16.0
  - bioconductor-kegg.db=3.2.4
  - bioconductor-genmicranges=1.42.0
  - bioconductor-rhdf5=2.34.0
  - pip:
    - cellex=1.2.1
    - cnmf=1.3.1


